import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
import json
from bson import json_util

'''
The serviceAccountKey.json file must be generated by firebase 
in the dashboard, settings, service account.
 '''
cred = credentials.Certificate('serviceAccountKey.json')
firebase_admin.initialize_app(cred)
firestore_client = firestore.client()

with open('firestore_backup.json') as json_file:
    json_data = json.load(json_file, object_hook=json_util.object_hook, )


def upload_database(data: dict, reference):
    for collectionName, documents in data.items():
        for documentId, documentContent in documents.items():
            documentData = documentContent['documentData']
            documentSubcollections = documentContent['documentSubcollections']
            documentReference = reference.collection(
                collectionName).document(documentId)
            # you may change it to [merge] False if you want to
            documentReference.set(documentData, merge=True)
            upload_database(data=documentSubcollections,
                            reference=documentReference)


upload_database(data=json_data, reference=firestore_client)

input('Press [enter] to exit...')
